---
# This playbook configures the AWS resources for the HHS Dev Cloud's 
# development infrastructure.
#
# Usage: This playbook should be included from `site.yml`.

- hosts: tag_Environment_{{ env }}:&tag_Name_ldap
  name: Configure 'ldap'
  user: ubuntu
  gather_facts: true
  become: true
  
  vars:
    jira_address_private: "{{ hostvars | get_members(groups, 'tag_Name_jira') | map(attribute='ec2_private_dns_name') | list | first }}"
    ldap_address_public: "{{ hostvars | get_members(groups, 'tag_Name_ldap') | map(attribute='ec2_public_dns_name') | list | first }}"
  
  roles:
    - ldap-server
  
  tasks:
    - name: Route 53 - ldap
      local_action: route53
        command=create
        overwrite=true
        zone=hhsdevcloud.us
        record="{{ ldap_dns }}"
        type=CNAME
        ttl=3600
        value="{{ ldap_address_public }}"
        # FIXME Not supported until Ansible release > 2.0.0.2
        # wait=true
      become: false

- hosts: tag_Environment_{{ env }}:&tag_Name_jira
  name: Configure 'jira'
  user: ubuntu
  gather_facts: true
  become: true
  
  vars:
    rds_instance_dev_name: "postgres-dev-{{ env }}"
    rds_postgres_dev_address: "{{ hostvars | get_members(groups, 'rds') | selectattr('ec2_id', 'equalto', rds_instance_dev_name) | map(attribute='ec2__address') | list | first }}"
    rds_postgres_dev_port: "{{ hostvars | get_members(groups, 'rds') | selectattr('ec2_id', 'equalto', rds_instance_dev_name) | map(attribute='ec2__port') | list | first }}"
  
  roles:
    - jira

- hosts: tag_Environment_{{ env }}:&tag_Name_jenkins_master
  name: Configure 'jenkins-master'
  user: ubuntu
  gather_facts: true
  become: true
  
  roles:
    - jenkins

- hosts: tag_Environment_{{ env }}:&tag_Name_dev_nginx
  name: Configure 'dev-nginx'
  user: ubuntu
  gather_facts: true
  become: true
  
  vars:
    jira_address_private: "{{ hostvars | get_members(groups, 'tag_Name_jira') | map(attribute='ec2_private_dns_name') | list | first }}"
    jenkins_address_private: "{{ hostvars | get_members(groups, 'tag_Name_jenkins_master') | map(attribute='ec2_private_dns_name') | list | first }}"
    dev_nginx_address_public: "{{ hostvars | get_members(groups, 'tag_Name_dev_nginx') | map(attribute='ec2_public_dns_name') | list | first }}"
  
  roles:
    - dev-nginx
  
  tasks:
    - name: Route 53 - issues
      local_action: route53
        command=create
        overwrite=true
        zone=hhsdevcloud.us
        record="{{ jira_dns }}"
        type=CNAME
        ttl=3600
        value="{{ dev_nginx_address_public }}"
        # FIXME Not supported until Ansible release > 2.0.0.2
        # wait=true
      become: false
    
    - name: Route 53 - jenkins
      local_action: route53
        command=create
        overwrite=true
        zone=hhsdevcloud.us
        record="{{ jenkins_dns }}"
        type=CNAME
        ttl=3600
        value="{{ dev_nginx_address_public }}"
        # FIXME Not supported until Ansible release > 2.0.0.2
        # wait=true
      become: false
