---
# This playbook manages the HHS Dev Cloud's development infrastructure:
# 
# * Java Build Servers: Jenkins, SonarQube, and Nexus
# * LDAP Server: Used to centralize user accounts for other servers
# * JIRA
# * etc. ...
#
# Usage:
#  
#     $ ansible-playbook -i ec2.py site.yml --extra-vars "env={ test | production }"

- include: site-provision.yml
- include: site-configure.yml
