---
#
# Variables here are applicable to the `ldap_server` role.
#

# Define all of the staff user+group entries to be created.
people:
  karldavis:
    givenName: Karl
    sn: Davis
    uidAndGidNumber: 10000
    mail: karl.davis@cms.hhs.gov
    password: "{{ vault_ldap_karldavis_password }}"
  markscrimshire:
    givenName: Mark
    sn: Scrimshire
    uidAndGidNumber: 10001
    mail: mark.scrimshire@cms.hhs.gov
    password: "{{ vault_ldap_markscrimshire_password }}"
  alanviars:
    givenName: Alan
    sn: Viars
    uidAndGidNumber: 10002
    mail: aviars@videntity.com
    password: "{{ vault_ldap_alanviars_password }}"
  lorimaattta:
    givenName: Lori
    sn: Maatta
    uidAndGidNumber: 10003
    mail: lori.maata@cms.hhs.gov
    password: "{{ vault_ldap_lorimaatta_password }}"
  carlymedosch:
    givenName: Carly
    sn: Medosch
    uidAndGidNumber: 10004
    mail: carly.medosch@cms.hhs.gov
    password: "{{ vault_ldap_carlymedosch_password }}"
  christinecox:
    givenName: Christine
    sn: Cox
    uidAndGidNumber: 10005
    mail: christine.cox@cms.hhs.gov
    password: "{{ vault_ldap_christinecox_password }}"
  niallbrennan:
    givenName: Niall
    sn: Brennan
    uidAndGidNumber: 10006
    mail: niall.brennan@cms.hhs.gov
    password: "{{ vault_ldap_niallbrennan_password }}"
  johndavis:
    givenName: John
    sn: Davis
    uidAndGidNumber: 10007
    mail: john.davis3@gdit.com
    password: "{{ vault_ldap_johndavis_password }}"
  scottwarren:
    givenName: Scott
    sn: Warren
    uidAndGidNumber: 10008
    mail: scott.warren@gdit.com
    password: "{{ vault_ldap_scottwarren_password }}"
  shaunbrockhoff:
    givenName: Shaun
    sn: Brockhoff
    uidAndGidNumber: 10009
    mail: shaun.brockhoff@gdit.com
    password: "{{ vault_ldap_shaunbrockhoff_password }}"
  scottkoerselman:
    givenName: Scott
    sn: Koerselman
    uidAndGidNumber: 10010
    mail: scott.koerselman@gdit.com
    password: "{{ vault_ldap_scottkoerselman_password }}"
  katiepandullo:
    givenName: Katie
    sn: Pandullo
    uidAndGidNumber: 10011
    mail: katie.pandullo@gdit.com
    password: "{{ vault_ldap_katiepandullo_password }}"
