---

- debconf: name=slapd question='slapd/domain' value='hhsdevcloud.us' vtype='string'
- debconf: name=slapd question='shared/organization' value='HHS IDEA Lab' vtype='string'
- debconf: name=slapd question='slapd/backend' value='HDB' vtype='string'
- debconf: name=slapd question='slapd/password1' value="{{ ldap_root_password }}" vtype='password'
- debconf: name=slapd question='slapd/password2' value="{{ ldap_root_password }}" vtype='password'

- name: Install
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - slapd
    - db-util
    - python-ldap

- ldap_entry: 
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'ou=people,dc=hhsdevcloud,dc=us'
    objectClass: ['organizationalUnit']
- ldap_entry:
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'ou=groups,dc=hhsdevcloud,dc=us'
    objectClass: ['organizationalUnit']
- ldap_entry:
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'ou=services,dc=hhsdevcloud,dc=us'
    objectClass: ['organizationalUnit']

- ldap_entry: 
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'uid=karldavis,ou=people,dc=hhsdevcloud,dc=us' 
    objectClass: ['inetOrgPerson', 'posixAccount']
    uid: karldavis
    cn: 'Karl M. Davis'
    displayName: 'Karl M. Davis'
    givenName: 'Karl'
    sn: 'Davis'
    uidNumber: '10000'
    gidNumber: '10000'
    userPassword: "{{ ldap_karldavis_password }}"
    loginShell: '/bin/bash'
    homeDirectory: '/home/karldavis'
    mail: 'karl.davis@cms.hhs.gov'
- ldap_entry:
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'cn=karldavis,ou=groups,dc=hhsdevcloud,dc=us'
    objectClass: 'posixGroup'
    cn: 'karldavis'
    gidNumber: '10000'

- ldap_entry: 
    bind_dn: 'cn=admin,dc=hhsdevcloud,dc=us'
    bind_pw: "{{ ldap_root_password }}"
    dn: 'cn=jira,ou=services,dc=hhsdevcloud,dc=us' 
    objectClass: ['organizationalRole', 'simpleSecurityObject']
    cn: jira
    userPassword: "{{ ldap_jira_password }}"

