---
# Be sure to see the role dependency in `../meta/main.yml`. It does most of the 
# work. This wrapping role just contains the customizations applied on top of 
# it.

- name: Install Build Tools
  apt: name={{ item }} state=installed
  become: true
  with_items: []

- name: "Configure Git (and activate git-lfs)"
  template:
    src: gitconfig.groovy
    dest: /var/lib/jenkins/.gitconfig
    owner: jenkins
    group: jenkins
    mode: 0664
  become: true

- name: Configure Jenkins Security
  template:
    src: configureSecurity.groovy
    dest: /var/lib/jenkins/init.groovy.d/configureSecurity.groovy
    owner: jenkins
    group: jenkins
    mode: 0744
  become: true
  notify:
    - "Restart Service 'jenkins'"

# This isn't actually being used right now, but at one point, I thought it was
# needed. Since it was a pain to create, and might be useful later, I'll leave 
# it.
- name: Configure Jenkins GitHub Plugin
  template:
    src: configureGitHub.groovy
    dest: /var/lib/jenkins/init.groovy.d/configureGitHub.groovy
    owner: jenkins
    group: jenkins
    mode: 0744
  become: true
  notify:
    - "Restart Service 'jenkins'"

- name: Maven - Configure Tool
  template:
    src: configureMaven.groovy
    dest: /var/lib/jenkins/init.groovy.d/configureMaven.groovy
    owner: jenkins
    group: jenkins
    mode: 0744
  become: true
  notify:
    - "Restart Service 'jenkins'"

- name: Maven - .m2
  file:
    path: /var/lib/jenkins/.m2
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

- name: Maven - Toolchains
  template:
    src: maven_toolchains.xml
    dest: /var/lib/jenkins/.m2/toolchains.xml
    owner: jenkins
    group: jenkins
    mode: 0644
  become: true
